---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: imagegenerationbackends.llm.knoway.dev
spec:
  group: llm.knoway.dev
  names:
    kind: ImageGenerationBackend
    listKind: ImageGenerationBackendList
    plural: imagegenerationbackends
    singular: imagegenerationbackend
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.provider
      name: Provider
      type: string
    - jsonPath: .spec.modelName
      name: Model Name
      type: string
    - jsonPath: .spec.upstream.baseUrl
      name: URL
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ImageGenerationBackend is the Schema for the imagegenerationbackends
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ImageGenerationBackendSpec defines the desired state of ImageGenerationBackend.
            properties:
              filters:
                description: Filters are applied to the model's requests
                items:
                  description: ImageGenerationFilter represents the image generation
                    backend filter configuration.
                  properties:
                    custom:
                      description: "Custom: Custom plugin configuration\nExample:\n\n\tcustom:\n\t\tpluginName:
                        examplePlugin\n\t\tpluginVersion: \"1.0.0\"\n\t\tsettings:\n
                        \ \t\tsetting1: value1\n  \t\tsetting2: value2"
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    name:
                      type: string
                  type: object
                type: array
              meteringPolicy:
                description: MeteringPolicy contains configurations about how to count
                  the usage of the model
                properties:
                  sizeFrom:
                    description: SizeFromInput indicates whether the size of the generated
                      image is determined by the input parameters.
                    enum:
                    - Input
                    - Output
                    - Greatest
                    type: string
                type: object
              modelName:
                description: ModelName specifies the name of the model
                type: string
              provider:
                description: Provider indicates the organization providing the model
                enum:
                - OpenAI
                - vLLM
                - Ollama
                - OpenAIV1Speech
                - DeepgramWebSocketV1
                - ElevenLabsV1
                - KoemotionV1
                - VolcengineSeedSpeechServiceV1
                - AlibabaCosyVoiceService
                - MicrosoftSpeechServiceV1
                type: string
              upstream:
                description: Upstream contains information about the upstream configuration
                properties:
                  RemoveParamKeys:
                    items:
                      type: string
                    type: array
                  baseUrl:
                    description: "BaseUrl define upstream endpoint url\nExample:\n\t\thttps://openrouter.ai/api/v1/chat/completions\n\n
                      \thttp://phi3-mini.default.svc.cluster.local:8000/api/v1/chat/completions"
                    type: string
                  defaultParams:
                    properties:
                      openai:
                        description: OpenAI model parameters
                        properties:
                          guidance_scale:
                            description: |-
                              Guidance scale is a number value that controls how much the conditional signal
                              (prompt, negative_prompt, training images, etc.) affects the generation epoch.
                              In Stable Diffusion, 7.5 is generally used.
                              For more information, see: https://sander.ai/2022/05/26/guidance.html
                            type: string
                          model:
                            type: string
                          "n":
                            description: N specifies the number of images to generate
                            type: string
                          negative_prompt:
                            description: NegativePrompt is a text description of the
                              undesired features of the image(s).
                            type: string
                          prompt:
                            description: A text description of the desired image(s).
                            type: string
                          quality:
                            description: |-
                              Quality specifies the quality of the image that will be generated.
                              hd creates images with finer details and greater consistency across the image.
                              Some of the model doesn't support this parameter.
                            type: string
                          response_format:
                            description: |-
                              ResponseFormat specifies the format in which the generated images are returned.
                              Must be one of url or b64_json.
                              URLs are only valid for 60 minutes after the image has been generated.
                            type: string
                          size:
                            description: |-
                              Size specifies the size of the generated images.
                              Must be one of 256x256, 512x512, or 1024x1024 for dall-e-2.
                              Must be one of 1024x1024, 1792x1024, or 1024x1792 for dall-e-3 models.
                            type: string
                          style:
                            description: |-
                              The style of the generated images.
                              Must be one of vivid or natural.
                              Vivid causes the model to lean towards generating hyper-real and dramatic images.
                              Natural causes the model to produce more natural, less hyper-real looking images.
                              This param is only supported for dall-e-3.
                            type: string
                          user:
                            description: |-
                              A unique identifier representing your end-user, which can help OpenAI to
                              monitor and detect abuse.
                            type: string
                        type: object
                    type: object
                  headers:
                    description: "Headers defines the common headers for the model,
                      such as the authentication header for the API key.\nExample:\n\nheaders：\n\t-
                      key: apikey\n\t  value: \"sk-or-v1-xxxxxxxxxx\""
                    items:
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  headersFrom:
                    description: "Headers defines the common headers for the model,
                      such as the authentication header for the API key.\nExample:\n\nheadersFrom：\n\t-
                      prefix: sk-or-v1-\n\t  refType: Secret\n\t  refName: common-gpt4-apikey"
                    items:
                      description: HeaderFromSource represents the source of a set
                        of ConfigMaps or Secrets
                      properties:
                        prefix:
                          description: An optional identifier to prepend to each key
                            in the ref.
                          type: string
                        refName:
                          description: Name of the source
                          type: string
                        refType:
                          description: Type of the source (ConfigMap or Secret)
                          enum:
                          - ConfigMap
                          - Secret
                          type: string
                      type: object
                    type: array
                  overrideParams:
                    properties:
                      openai:
                        description: OpenAI model parameters
                        properties:
                          guidance_scale:
                            description: |-
                              Guidance scale is a number value that controls how much the conditional signal
                              (prompt, negative_prompt, training images, etc.) affects the generation epoch.
                              In Stable Diffusion, 7.5 is generally used.
                              For more information, see: https://sander.ai/2022/05/26/guidance.html
                            type: string
                          model:
                            type: string
                          "n":
                            description: N specifies the number of images to generate
                            type: string
                          negative_prompt:
                            description: NegativePrompt is a text description of the
                              undesired features of the image(s).
                            type: string
                          prompt:
                            description: A text description of the desired image(s).
                            type: string
                          quality:
                            description: |-
                              Quality specifies the quality of the image that will be generated.
                              hd creates images with finer details and greater consistency across the image.
                              Some of the model doesn't support this parameter.
                            type: string
                          response_format:
                            description: |-
                              ResponseFormat specifies the format in which the generated images are returned.
                              Must be one of url or b64_json.
                              URLs are only valid for 60 minutes after the image has been generated.
                            type: string
                          size:
                            description: |-
                              Size specifies the size of the generated images.
                              Must be one of 256x256, 512x512, or 1024x1024 for dall-e-2.
                              Must be one of 1024x1024, 1792x1024, or 1024x1792 for dall-e-3 models.
                            type: string
                          style:
                            description: |-
                              The style of the generated images.
                              Must be one of vivid or natural.
                              Vivid causes the model to lean towards generating hyper-real and dramatic images.
                              Natural causes the model to produce more natural, less hyper-real looking images.
                              This param is only supported for dall-e-3.
                            type: string
                          user:
                            description: |-
                              A unique identifier representing your end-user, which can help OpenAI to
                              monitor and detect abuse.
                            type: string
                        type: object
                    type: object
                  timeout:
                    format: int32
                    type: integer
                type: object
            type: object
          status:
            description: ImageGenerationBackendStatus defines the observed state of
              ImageGenerationBackend.
            properties:
              conditions:
                description: Conditions represent the current conditions of the backend
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              endpoints:
                description: Endpoints holds the upstream addresses of the current
                  model (pod IP addresses)
                items:
                  type: string
                type: array
              status:
                description: 'Status indicates the health of the backend: Unknown,
                  Healthy, or Failed'
                enum:
                - Unknown
                - Healthy
                - Failed
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
